name: joliby_tv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # متوافقة تماماً مع سيرفر جيت هاب بدون مشاكل

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.8.6 # نسخة مستقرة وممتازة وتتحمل بدون مشاكل الـ Bintray القديمة

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


